# Generated by Django 4.2.8 on 2023-12-16 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegos',
            old_name='cuerpo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='juegos',
            old_name='subnombre',
            new_name='plataforma',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 30, 50, 698429)),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 30, 50, 697429)),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
