# Generated by Django 4.2.8 on 2023-12-15 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0003_juegos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 21, 15, 23, 816077)),
        ),
    ]
