# Generated by Django 4.2.8 on 2023-12-15 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0004_alter_juegos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='cuerpo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 19, 51, 40, 869916)),
        ),
    ]
